channels:
- conda-forge
dependencies:
- python=3.8.10
- pip
- pip:
  - pyspark
  - mlflow
  - matplotlib
  - cloudpickle==1.6.0
  - pandas==1.2.4
  - psutil==5.8.0
  - scikit-learn==0.24.1
  - typing-extensions==3.7.4.3
  - xgboost==1.4.2
name: mlflow-env
